# Generated by Django 5.1.6 on 2025-02-17 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver_model',
            name='Experience',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='driver_model',
            name='License',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='driver_model',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
