# Generated by Django 5.1.6 on 2025-02-17 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_driver_model_experience_driver_model_license_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver_model',
            name='gender',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
