# Generated by Django 5.1.6 on 2025-02-18 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_driver_model_bus_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driver_model',
            old_name='Experience',
            new_name='experience',
        ),
        migrations.RenameField(
            model_name='driver_model',
            old_name='License',
            new_name='license',
        ),
    ]
