# Generated by Django 5.1.6 on 2025-02-20 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_rename_experience_driver_model_experience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='login_model',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
