# Generated by Django 5.1.6 on 2025-02-20 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_login_model_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='busroute_model',
            name='bus_id',
        ),
        migrations.AddField(
            model_name='bus_model',
            name='OWNERID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.login_model'),
        ),
    ]
