# Generated by Django 5.1.6 on 2025-02-20 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_busroute_model_bus_id_bus_model_ownerid'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus_model',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
